/* Home editorial: papelaria científica e acesso aos três módulos. */
(()=>{
"use strict";
const A=window.PHY_APP,{terms,subjects,state,h,pill,button,metric,page,register,modules}=A;
const firstUnread=()=>subjects.find(s=>!state.read.includes(s.id+"/conceito"))||subjects[0];
const termCard=t=>'<a class="term-card term-'+t.number+'" href="#periodo/'+t.number+'"><span class="term-symbol">'+h(t.symbol)+'</span><small>'+t.number+'º PERÍODO</small><h3>'+h(t.title)+'</h3><p>Explore os temas e modelos do período</p><b>Explorar período ↗</b></a>';
const home=()=>{
 const first=firstUnread(),total=subjects.reduce((n,s)=>n+s.flashcards.length,0);
 return page(
 '<section class="home-hero"><div class="hero-grid" aria-hidden="true"></div><div class="home-hero-content"><span class="eyebrow">MEU UNIVERSO ACADÊMICO · FÍSICA</span><h1>Estudar, experimentar e <em>descobrir o universo.</em></h1><p>Seu caderno completo para explorar teorias, compreender equações, treinar o raciocínio e guardar as ideias mais importantes da graduação.</p><div class="hero-pills">'+pill("∇ Teoria e aplicações")+pill("λ Revisão ativa")+pill("✧ Pesquisa e referências")+'</div><div class="hero-buttons"><a href="#resumos" class="btn btn-primary">Começar meus estudos →</a><a href="#flashcards" class="btn btn-soft">Revisar com flashcards</a></div></div><div class="home-cosmos" aria-hidden="true"><div class="atom"><div class="atom-ring ring-one"></div><div class="atom-ring ring-two"></div><div class="atom-ring ring-three"></div><strong>φ</strong><i>✦</i></div><span class="cosmos-formula">E = mc² &nbsp; · &nbsp; ∇×B</span><div class="cosmos-note note-a"><b>✧ Pequenas descobertas</b><span>Uma equação de cada vez</span></div><div class="cosmos-note note-b"><b>∮ Meu laboratório</b><span>Pensar · testar · descobrir</span></div></div></section>'+
 '<section class="home-welcome"><div><span class="eyebrow">SEU CADERNO, SEU PRÓXIMO CAPÍTULO</span><h2>Uma nova ideia começa aqui <span aria-hidden="true">✷</span></h2><p>Marque leituras, registre suas explicações e retome seus assuntos preferidos sempre que quiser.</p></div><aside><b>✎ Caderno de descobertas</b><span>A teoria ganha sentido quando você faz boas perguntas.</span></aside></section>'+
 '<section class="home-modules"><div class="section-title"><div><span class="eyebrow">SEUS ESPAÇOS PARA APRENDER</span><h2>Escolha seu próximo capítulo</h2></div><span class="handwritten">curiosidade sempre em movimento ✧</span></div><div class="module-grid">'+modules.map((m,i)=>'<a class="module-card module-card-'+(i+1)+'" href="#'+m.id+'"><div class="module-cover"><span class="module-symbol">'+m.icon+'</span><span class="module-small">'+h(m.tag)+'</span><span class="module-formula" aria-hidden="true">'+["∫ F · dr","ψ(x,t)","∇ · E"][i]+'</span></div><div class="module-description"><h3>'+h(m.title)+'</h3><p>'+h(m.description)+'</p><footer><b>'+h(m.action)+'</b><i>↗</i></footer></div></a>').join("")+'</div></section>'+
 '<section class="continue"><span class="continue-icon">∑</span><div><span class="eyebrow">CONTINUE A INVESTIGAÇÃO</span><h3>'+h(first.title)+'</h3><p>'+h(first.concept.slice(0,205))+'…</p></div><a class="btn btn-primary" href="#leitura/'+first.id+'/conceito">Abrir leitura →</a></section>'+
 '<section class="home-terms"><div class="section-title"><div><span class="eyebrow">SUA TRILHA PELA GRADUAÇÃO</span><h2>Conheça os períodos</h2></div></div><div class="term-grid">'+terms.map(termCard).join("")+'</div></section>','home-page');
};
const search=()=>page('<div class="search-banner"><span class="eyebrow">BUSCA ACADÊMICA</span><h1>Uma boa pergunta abre caminhos.</h1><p>Pesquise disciplinas, áreas e fontes para aprender mais sobre Física.</p><label>O que vamos descobrir?<input data-search type="search" placeholder="Ex.: Mecânica Quântica, Fourier, termodinâmica..." autofocus></label></div><section class="content-block"><h2>Disciplinas e conteúdos</h2><div class="subject-grid">'+subjects.map(s=>'<a class="subject-search filter-card" data-keywords="'+h((s.title+" "+s.area+" "+s.concept).toLowerCase())+'" href="#leitura/'+s.id+'/conceito"><span>'+h(s.semester)+'º período · '+h(s.area)+'</span><h3>'+h(s.title)+'</h3><p>'+h(s.concept.slice(0,140))+'…</p><b>Abrir resumo →</b></a>').join("")+'</div></section><section class="content-block"><h2>Fontes bibliográficas</h2><div class="search-ref-grid">'+A.allBooks().map(b=>'<a class="reference-search filter-card" data-keywords="'+h((b.title+" "+b.authors+" "+b.topic).toLowerCase())+'" href="#bibliografia"><b>'+h(b.title)+'</b><span>'+h(b.authors)+'</span></a>').join("")+'</div></section>','search-page');
register("home",home);register("busca",search);
window.PHY_HOME={termCard};
})();